name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@latest
        with:
          version: "18.1"
          cached: true
      
      - name: Setup CMake and Ninja
        uses: lukka/get-cmake@latest
      
      - name: Restore CPM Cache
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/build/_deps
          key: cpm-cache-clang-${{ runner.os }}-${{ hashFiles('CMakeLists.txt', 'cmake/CPM.cmake')}}
          restore-keys: cpm-cache-clang-${{ runner.os }}-
      
      - name: Cache CMake Build
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/build
            !${{ github.workspace }}/build/_deps
          key: cmake-build-clang-${{ runner.os }}-${{ hashFiles('CMakeLists.txt') }}-${{ hashFiles('src/**/*.cpp', 'src/**/*.h') }}
          restore-keys: cmake-build-clang-${{ runner.os }}-
      
      - name: Configure CMake
        run: cmake --preset default
      
      - name: Build Release
        run: cmake --build build --config Release
      
      - name: Build Debug
        run: cmake --build build --config Debug
      
      - name: Create Release directory structure
        run: |
          New-Item -ItemType Directory -Force -Path release-package
          New-Item -ItemType Directory -Force -Path release-package/assets
          Copy-Item build/Release/funny-keyboard.exe release-package/
          if (Test-Path assets) {
            Copy-Item -Recurse assets/* release-package/assets/
          }
      
      - name: Create Debug directory structure
        run: |
          New-Item -ItemType Directory -Force -Path debug-package
          New-Item -ItemType Directory -Force -Path debug-package/assets
          Copy-Item build/Debug/funny-keyboard.exe debug-package/
          Copy-Item build/Debug/funny-keyboard.pdb debug-package/
          if (Test-Path assets) {
            Copy-Item -Recurse assets/* debug-package/assets/
          }
      
      - name: Create Release zip
        run: Compress-Archive -Path release-package/* -DestinationPath funny-keyboard.zip
      
      - name: Create Debug zip
        run: Compress-Archive -Path debug-package/* -DestinationPath funny-keyboard-debug.zip
      
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          body: |
            | Release  | Debug    |
            |----------|----------|
            | [Download](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/funny-keyboard.zip) | [Download](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/funny-keyboard-debug.zip) |

            Default assets are included.
            Download and extract the appropriate zip file
            Run `funny-keyboard.exe`
            Press `Ctrl+Alt+F` to exit
          generate_release_notes: true
          files: |
            funny-keyboard.zip
            funny-keyboard-debug.zip
